export const LEAGUES = [
  {
    id: '1',
    name: 'Bronze',
    image: require('../assets/images/league/1.png'),
    min: 0,
    max: 199,
  },
  {
    id: '2',
    name: 'Silver',
    image: require('../assets/images/league/2.png'),
    min: 200,
    max: 399,
  },
  {
    id: '3',
    name: 'Gold',
    image: require('../assets/images/league/3.png'),
    min: 400,
    max: 599,
  },
  {
    id: '4',
    name: 'Platinum',
    image: require('../assets/images/league/4.png'),
    min: 600,
    max: 799,
  },
  {
    id: '5',
    name: 'Diamond',
    image: require('../assets/images/league/5.png'),
    min: 800,
    max: 999,
  },
  {
    id: '6',
    name: 'Master',
    image: require('../assets/images/league/6.png'),
    min: 1000,
    max: 1199,
  },
  {
    id: '7',
    name: 'Challenger',
    image: require('../assets/images/league/7.png'),
    min: 1200,
    max: 1399,
  },
  {
    id: '8',
    name: 'Ruby',
    image: require('../assets/images/league/8.png'),
    min: 1400,
    max: 1599,
  },
  {
    id: '9',
    name: 'Sapphire',
    image: require('../assets/images/league/9.png'),
    min: 1600,
    max: 1799,
  },
  {
    id: '10',
    name: 'Emerald',
    image: require('../assets/images/league/10.png'),
    min: 1800,
    max: 1999,
  },
];
